//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_PROJECT_e_Adminstrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_TB
    {
        public Lab_TB()
        {
            this.Lab_Time_TB = new HashSet<Lab_Time_TB>();
        }
    
        public int ID { get; set; }
        public string Lab_Name { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual ICollection<Lab_Time_TB> Lab_Time_TB { get; set; }
    }
}
