//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_PROJECT_e_Adminstrator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sudent_TB
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string FATHER_NAME { get; set; }
        public string CNIC { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PHONE { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> BATCH_ID { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual Batch_TB Batch_TB { get; set; }
    }
}
